encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.wiki, name="wiki"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name = "create"),
    path("edit/<str:name>",views.edit, name ="edit"),
    path("save/<str:name>",views.save, name ="save"),
    path("random/",views.random_choser,name = "random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create Page</h1>

    <form action = "{% url 'encyclopedia:create'%}" method = "post">
        {% csrf_token %}
        {{ message }}
        <div>
        <label for="id_title">Title:</label>
        <br>
        <input type="text" name="title" required="" id="id_title" placeholder="Enter Title Name"/>
        {{ error }}
        </div>
        <div> 
        <label for="desc">Description:</label>
        <br>
        <textarea id = "desc" name = "description" style="height: 286px;resize:none;"></textarea>
         <div>
         <input type = "submit" value = "submit" />
         
      </form> 

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>

    <form action = "{% url 'encyclopedia:save' name %}" method = "post">
        {% csrf_token %}
        <div> 
        <label for="desc">Description:</label>
        <br>
        <textarea id = "desc" name = "description" style="height: 286px;resize:none;">{{ desc }}</textarea>
         <div>
         <input type = "submit" value = "Save" />
         
      </form> 

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        
        <li><a href="{% url 'encyclopedia:wiki' entry %}">{{entry}}</a></li>
        {% empty %}
        {{error}}

        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <ul>
        {% for entry in entries %}
        
        <li><a href="{% url 'encyclopedia:wiki' entry %}">{{entry}}</a></li>
        {% empty %}
        Search Term Not Found

        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
{{ desc|safe }}
<button type = "button" onclick="location.href='{% url 'encyclopedia:edit' name %}'">Edit</button>
{% endblock %}